services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: micro_services_db
    volumes:
      - mongo_data:/data/db

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/micro_services_db?authSource=admin
    depends_on:
      - mongodb

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=3002
    depends_on:
      - user-service

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=3001
    depends_on:
      - auth-service

volumes:
  mongo_data:
