services:
  mongo:
    image: mongo:latest
    container_name: p3-bai2-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  app:
    build: ./app
    container_name: p3-bai2-nodejs
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/mydb
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - app-net

volumes:
  mongo_data:

networks:
  app-net:
